# Generated by Django 4.0.5 on 2022-06-23 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('speciality', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='Profle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('bio', models.CharField(max_length=100000)),
                ('phone', models.IntegerField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.profle')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service', models.CharField(choices=[('Grooming', 'Grooming'), ('Vaccination', 'Vaccination'), ('Diet and Nutrition', 'Diet and Nutrition'), ('Weight Mnagement', 'Weight Management'), ('Behavior', 'Behavior'), ('Oral and Dental Exam', 'Oral and Dental Exam'), (' Photoshoot', ' Photoshoot')], max_length=35)),
                ('time_booked', models.CharField(choices=[('0800hrs', '0800-0900'), ('0930hrs', '0930-1130'), ('noon', '1200-0130'), ('1400hrs', '0200-0300'), ('1530hrs', '0330-0430')], max_length=10)),
                ('when_the_booking_was_done', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet.pet')),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.profle')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='the_vet', to='pet.vet')),
            ],
        ),
    ]
