# Generated by Django 3.2.13 on 2022-06-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='kind',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
